### ISSUE TITLE
installation fails on Python 2.7.10

### ISSUE THREAD

**Issue by robertoostenveld** [rhjdjong/SlipLib#2]
```
mbp> sudo pip install sliplib
Collecting sliplib
  Downloading sliplib-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-_daxho/sliplib/setup.py", line 12, in <module>
        import sliplib
      File "sliplib/__init__.py", line 16, in <module>
        from .slip import (encode, decode, SlipDecodingError,
      File "sliplib/slip.py", line 114, in <module>
        encode = partial(SlipEncoder().encode, errors=None, final=True)
      File "sliplib/slip.py", line 38, in __init__
        super().__init__(*args, **kwargs)
    TypeError: super() takes at least 1 argument (0 given)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-_daxho/sliplib/
```

Trying to install it directly from github:
```
mbp> sudo pip install -e git+https://github.com/rhjdjong/SlipLib.git#egg=sliplib
Obtaining sliplib from git+https://github.com/rhjdjong/SlipLib.git#egg=sliplib
  Updating ./src/sliplib clone
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/robert/src/sliplib/setup.py", line 12, in <module>
        import sliplib
      File "sliplib/__init__.py", line 16, in <module>
        from .slip import (encode, decode, is_valid, Driver, ProtocolError)
      File "sliplib/slip.py", line 22
        def encode(msg: bytes) -> bytes:
                      ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/robert/src/sliplib/
```

Might it be that it needs a newer Python version?

**Comment by rhjdjong** [comment]
Thanks for your interest in sliplib. However, sliplib is still very much work-in-progress, as you can see by the development status (alpha) and version number (0.0.1).  I try to work on this in my spare time, which is not often unfortunately. The latest GitHub code has not yet been pushed to PyPI,; that explains the differences you see in installing via PyPI or directly from GitHub. The current version in GitHub is the (unfinished) result of a major rewrite, based on the insight that encoding/decoding functions should be decoupled from the byte streaming and networking parts. But anyway, this is all developed for Python 3.2 or later.

**Comment by robertoostenveld** [comment]
thanks, no worries. I just wanted to give you some feedback that you might want to use in development and/or documentation.
